# Generated by Django 4.2.25 on 2025-11-03 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcoderesult',
            options={'verbose_name': 'Баркод', 'verbose_name_plural': 'Баркоды'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='photobatch',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Карточка товара', 'verbose_name_plural': 'Карточки товаров'},
        ),
        migrations.AlterModelOptions(
            name='processingtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача обработки', 'verbose_name_plural': 'Задачи обработки'},
        ),
        migrations.AlterField(
            model_name='barcoderesult',
            name='data',
            field=models.CharField(max_length=500, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='barcoderesult',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='photos.photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='barcoderesult',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='barcoderesult',
            name='symbology',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photobatch', verbose_name='Карточка товара'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_id',
            field=models.CharField(max_length=255, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='message_id',
            field=models.BigIntegerField(verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='correlation_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='ID карточки'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='message_ids',
            field=models.JSONField(default=list, verbose_name='ID сообщений'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processed', 'Обработано'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photobatch',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='api_name',
            field=models.CharField(max_length=100, verbose_name='API'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='photos.photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='processingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
