# Generated by Django 4.2.25 on 2025-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_barcoderesult_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobatch',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('used', 'Б/у'), ('refurbished', 'Восстановленное')], max_length=50, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='sku',
            field=models.CharField(blank=True, max_length=200, verbose_name='SKU/Артикул'),
        ),
        migrations.AddField(
            model_name='photobatch',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название товара'),
        ),
    ]
