# Generated by Django 4.2.25 on 2025-11-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photobatch_brand_photobatch_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-is_main', 'order', 'uploaded_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
