# Generated by Django 4.2.25 on 2025-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_options_photo_is_main_photo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobatch',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='AI Сводка'),
        ),
    ]
