# Generated by Django 4.2.25 on 2025-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photobatch_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobatch',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
