# Generated by Django 4.2.25 on 2025-11-05 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photobatch_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram File ID')),
                ('message_id', models.BigIntegerField(verbose_name='Message ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('image', models.ImageField(upload_to='buffer/%Y/%m/%d/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружено')),
                ('gg_label', models.CharField(blank=True, max_length=50, verbose_name='GG лейбл')),
                ('barcode', models.CharField(blank=True, max_length=200, verbose_name='Баркод')),
                ('group_id', models.IntegerField(blank=True, null=True, verbose_name='Группа')),
                ('group_order', models.IntegerField(default=0, verbose_name='Порядок в группе')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('sent_to_bot', models.BooleanField(default=False, verbose_name='Отправлено в бота')),
            ],
            options={
                'verbose_name': 'Фото в буфере',
                'verbose_name_plural': 'Фото в буфере',
                'ordering': ['group_id', 'group_order', 'uploaded_at'],
            },
        ),
    ]
