# Generated by Django 4.2.26 on 2025-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0007_photobuffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="photobatch",
            name="locations",
            field=models.JSONField(blank=True, default=list, verbose_name="Locations"),
        ),
    ]
