"""
Django settings for shoessite project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Optional Sentry initialization (safe if SDK not installed or DSN empty)
SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
SENTRY_ENV = os.getenv("SENTRY_ENV")  # may be None; set later after DEBUG is known

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add parent directory to path for apps module
sys.path.insert(0, str(BASE_DIR.parent))

# Load .env file if it exists
# Try multiple locations: project root, parent of BASE_DIR, and BASE_DIR
env_locations = [
    BASE_DIR.parent.parent / '.env',  # /home/pochtoy/shoesbot/.env
    BASE_DIR.parent / '.env',         # /home/pochtoy/shoesbot/shoessite/.env
    BASE_DIR / '.env',                # /home/pochtoy/shoesbot/shoessite/shoessite/.env
]

env_file = None
for loc in env_locations:
    if loc.exists():
        env_file = loc
        break

if env_file:
    from dotenv import load_dotenv
    load_dotenv(env_file)
    print(f"✅ Загружен .env из: {env_file}")
else:
    print(f"⚠️ .env файл не найден. Проверенные пути: {env_locations}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5jp&emf6g8@x3-8$!86hwmv=(_(@izc0_5s(*_n$5^k7ce^$$v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = ['https://pochtoy.us', 'https://www.pochtoy.us']

# Увеличиваем лимит для загрузки фоток из бота
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'django_filters',

    # Local apps
    'photos',
    'apps.marketplaces.ebay',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoessite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoessite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR.parent / 'static'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Change in production
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# =============================================================================
# EBAY MARKETPLACE SETTINGS
# =============================================================================

# eBay Environment
EBAY_SANDBOX = True  # Set to False for production

# eBay API Credentials
# eBay API Keys (loaded from .env)
EBAY_APP_ID = os.getenv('EBAY_APP_ID', '')
EBAY_DEV_ID = os.getenv('EBAY_DEV_ID', '')
EBAY_CERT_ID = os.getenv('EBAY_CERT_ID', '')
EBAY_SANDBOX = os.getenv('EBAY_SANDBOX', 'true').lower() == 'true'  # Default to sandbox

# Photo hosting
PHOTO_HOST_DOMAIN = 'https://pochtoy.us'

# GPT/AI Settings
GPT_PROVIDER = 'openai'  # stub for now

# Pricing Settings
PRICE_BELOW_MEDIAN_PCT = 0.08  # 8% below market median
DEFAULT_SHIP_COST = 4.99  # Default shipping cost

# Celery Settings (optional, configure if using Celery)
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# =============================================================================
# Sentry (error monitoring)
# =============================================================================

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration

        # Derive environment if not explicitly set
        environment = SENTRY_ENV or ("development" if DEBUG else "production")

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                LoggingIntegration(level=None, event_level=None),
            ],
            traces_sample_rate=float(os.getenv("SENTRY_TRACES", "0.05")),
            profiles_sample_rate=float(os.getenv("SENTRY_PROFILES", "0.0")),
            send_default_pii=False,
            environment=environment,
        )
        print(f"✅ Sentry enabled (env={environment})")
    except Exception as _sentry_err:
        # Never fail settings because of Sentry
        print(f"⚠️ Sentry init skipped: {_sentry_err}")

# =============================================================================
# GOOGLE CLOUD STORAGE для защиты фото (опционально)
# =============================================================================

USE_GCS = os.environ.get('USE_GCS', 'false').lower() == 'true'

if USE_GCS and not DEBUG:
    # Требует установки: pip install django-storages[google] google-cloud-storage
    DEFAULT_FILE_STORAGE = 'storages.backends.gcs.GSGoogleCloudStorage'
    GS_BUCKET_NAME = 'shoesbot-media-prod'
    GS_PROJECT_ID = 'pochtoy'
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
    print("✅ Google Cloud Storage enabled for media")

# =============================================================================
# PRODUCTION OVERRIDES - НЕ ТРОГАТЬ при rsync
# =============================================================================

if not os.environ.get('DEV_MODE'):
    # Production настройки для статики и медиа
    STATIC_ROOT = '/var/www/shoesbot/static/'
    STATIC_URL = '/static/'
    if not USE_GCS:
        MEDIA_ROOT = '/home/pochtoy/shoesbot/shoessite/media'
        MEDIA_URL = '/media/'
