# Generated by Django 4.2.26 on 2025-11-11 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photos", "0008_photobatch_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="EbayToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        default="default",
                        help_text="Account identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, help_text="eBay OAuth access token"),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="eBay OAuth refresh token"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Access token expiration timestamp",
                        null=True,
                    ),
                ),
                (
                    "sandbox",
                    models.BooleanField(
                        default=True, help_text="Use sandbox environment"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "eBay Token",
                "verbose_name_plural": "eBay Tokens",
            },
        ),
        migrations.CreateModel(
            name="EbayCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("listed", "Listed"),
                            ("error", "Error"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the listing",
                        max_length=20,
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        blank=True, help_text="eBay category ID", max_length=50
                    ),
                ),
                (
                    "ebay_item_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="eBay item ID once listed",
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("NEW_OTHER", "New Other"),
                            ("NEW_WITH_DEFECTS", "New with Defects"),
                            ("MANUFACTURER_REFURBISHED", "Manufacturer Refurbished"),
                            ("CERTIFIED_REFURBISHED", "Certified Refurbished"),
                            ("SELLER_REFURBISHED", "Seller Refurbished"),
                            ("LIKE_NEW", "Like New"),
                            ("USED_EXCELLENT", "Used - Excellent"),
                            ("USED_VERY_GOOD", "Used - Very Good"),
                            ("USED_GOOD", "Used - Good"),
                            ("USED_ACCEPTABLE", "Used - Acceptable"),
                            ("FOR_PARTS_OR_NOT_WORKING", "For Parts or Not Working"),
                        ],
                        help_text="Item condition",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="eBay listing title (max 80 chars)",
                        max_length=80,
                    ),
                ),
                (
                    "description_md",
                    models.TextField(blank=True, help_text="Markdown description"),
                ),
                (
                    "specifics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Item specifics (key-value pairs)",
                    ),
                ),
                (
                    "price_suggested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI-suggested price based on comps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final listing price (includes shipping)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "comps",
                    models.JSONField(
                        blank=True, default=list, help_text="Comparable listings data"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of photo URLs for eBay",
                    ),
                ),
                (
                    "policies",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business policies (shipping, return, payment)",
                    ),
                ),
                (
                    "heavy_flag",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Requires special handling (heavy/oversized)",
                    ),
                ),
                (
                    "logs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Operation logs (API calls, errors, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("listed_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "photo_batch",
                    models.ForeignKey(
                        help_text="Source photo batch for this listing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ebay_candidates",
                        to="photos.photobatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "eBay Candidate",
                "verbose_name_plural": "eBay Candidates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ebay_ebayca_status_fd2f28_idx",
                    ),
                    models.Index(
                        fields=["photo_batch", "status"],
                        name="ebay_ebayca_photo_b_9ceb9e_idx",
                    ),
                ],
            },
        ),
    ]
